baseurl         = "/"
theme           = "hugo-casper-two"
languageCode    = "es-ES"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "LA JAURIA"
  subtitle    = ""
  copyright   = "© 2018"

  cover       = "img/la-jauria.gif"
  description = "Este sitio pretende dar a conocer el trabajo realizado en La Jauria, además de permitir la comunicación ágil."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  youtube = "UCGXVQ6HSCHy9Mw3XwANYnJw?view_as=subscriber"
  fbName = "juguetesjauria"
  instagramLink = "lajauria_circuit_orchestra/?hl=es-la"
  githubName = "rakeemr"

  logo = "jauria.png"
  orgName = "La Jauria"
  orgWebsite = "https://www.lajauria.net"
  orgDescription = ""

  showSupport = true

  author = "La Jauria"
  authorAvatar = "la-jauria.png"
  authorLocation = ""
  authorWebsite = "https://eueung.github.io"
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Talleres"
  url = "/talleres/"
  weight = 100

[[menu.main]]
  name = "Proyectos"
  url = "/proyectos/"
  weight = 99

[[menu.main]]
  name = "Contáctanos"
  url = "/contacto/"
  weight = 95
