baseurl         = "/"
theme           = "hugo-casper-two"
languageCode    = "es-ES"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "LA JAURIA"
  subtitle    = ""
  copyright   = "© 2018"

  cover       = "img/la-jauria.gif"
  description = "Este sitio pretende dar a conocer el trabajo realizado en La Jauria, además de permitir la comunicación ágil."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  youtube = "UCGXVQ6HSCHy9Mw3XwANYnJw?view_as=subscriber"
  fbName = "juguetesjauria"
  instagramLink = "lajauria_circuit_orchestra/?hl=es-la"

  logo = "jauria.png"
  orgName = "La Jauria"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "La Jauria"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = ""
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95
